In [1]:
import torch

In [2]:
batch = torch.rand(1, 12, 207, 2)
batch.shape

torch.Size([1, 12, 207, 2])

In [12]:
mask = torch.ones(12, 2)
mask[4, 0] = 0
mask[2, 1] = 0
mask

tensor([[1., 1.],
        [1., 1.],
        [1., 0.],
        [1., 1.],
        [0., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [18]:
res = torch.einsum('xy, abcd -> abxy', mask, batch.transpose(1, 2))

In [19]:
res.shape

torch.Size([1, 207, 12, 2])

In [21]:
res[0, :, 4]

tensor([[ 0.0000, 11.1622],
        [ 0.0000, 11.4142],
        [ 0.0000, 13.8607],
        [ 0.0000, 13.3038],
        [ 0.0000, 13.8653],
        [ 0.0000, 12.4384],
        [ 0.0000, 10.4786],
        [ 0.0000, 12.0187],
        [ 0.0000, 13.1119],
        [ 0.0000, 10.3670],
        [ 0.0000, 13.5061],
        [ 0.0000, 10.9516],
        [ 0.0000,  9.5960],
        [ 0.0000, 10.8785],
        [ 0.0000, 12.6371],
        [ 0.0000, 11.6308],
        [ 0.0000, 11.9078],
        [ 0.0000, 14.4539],
        [ 0.0000, 10.9412],
        [ 0.0000, 11.1351],
        [ 0.0000,  9.5773],
        [ 0.0000, 12.3783],
        [ 0.0000, 11.1048],
        [ 0.0000, 12.3250],
        [ 0.0000, 12.4069],
        [ 0.0000, 12.8743],
        [ 0.0000, 11.0114],
        [ 0.0000, 12.4139],
        [ 0.0000, 11.2009],
        [ 0.0000, 11.6385],
        [ 0.0000, 12.3249],
        [ 0.0000, 11.1137],
        [ 0.0000, 11.2161],
        [ 0.0000, 10.4822],
        [ 0.0000, 13.2504],
        [ 0.0000, 12

In [23]:
res[0, :, 2, 0]

tensor([11.1622, 11.4142, 13.8607, 13.3038, 13.8653, 12.4384, 10.4786, 12.0187,
        13.1119, 10.3670, 13.5061, 10.9516,  9.5960, 10.8785, 12.6371, 11.6308,
        11.9078, 14.4539, 10.9412, 11.1351,  9.5773, 12.3783, 11.1048, 12.3250,
        12.4069, 12.8743, 11.0114, 12.4139, 11.2009, 11.6385, 12.3249, 11.1137,
        11.2161, 10.4822, 13.2504, 12.3309, 10.4570, 11.2913, 11.4987, 12.2859,
        14.6137, 14.2412, 10.4556,  9.3400, 12.3831, 12.4343, 11.2301, 11.4548,
        13.8625, 10.6523, 10.9591, 11.8519, 11.2553, 10.6832, 10.8172, 11.4724,
        11.4530, 10.1501, 12.2320, 11.1690, 11.6476, 13.6019, 14.4900, 10.8972,
        11.7074, 12.8025, 12.0011, 11.8795, 12.4478, 13.2408, 13.6933, 10.3077,
        12.2002, 13.5176, 11.9820, 12.9184, 13.1318, 12.1680, 11.2881, 12.5195,
        14.3656,  9.2162, 12.1422, 11.0044,  9.6079, 13.5140, 10.4504, 12.9099,
        12.5912, 12.6131, 11.0427,  8.6806, 13.5181, 11.0056, 11.2424, 10.3728,
        12.5659, 13.3344, 11.7537, 14.05